-- --------------------------------------------------------
-- AUTO-GENERATED by build_pipeline.py's sql-export step -- do not hand-edit.
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table mangos.achievement_retirement
DROP TABLE IF EXISTS `achievement_retirement`;
CREATE TABLE `achievement_retirement` (
  `retired_achievement_id` mediumint(8) unsigned NOT NULL,
  `replacement_achievement_id` mediumint(8) unsigned DEFAULT NULL,
  `patch` tinyint(3) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`retired_achievement_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci ROW_FORMAT=FIXED COMMENT='Achievment system - retires an achievement into Feats of Strength once its replacement patch is reached';

-- Dumping data for table mangos.achievement_retirement: 1 rows
INSERT INTO `achievement_retirement` (`retired_achievement_id`, `replacement_achievement_id`, `patch`) VALUES
	(4826, 4828, 1);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
